config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  resources :chats
  get '/dashboard', to: 'chats#index'
  root 'chatrooms#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  after_create :notify_pusher
  belongs_to :chatroom

  def notify_pusher
    Pusher.trigger('chat', 'new-chat', self.as_json)
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  after_create :notify_pusher
  has_many :chats

  def notify_pusher
    Pusher.trigger('chat', 'new-chatroom', self.as_json)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatroom = Chatroom.new
  end
  def new
    @chatroom = Chatroom.new
  end
  def create
    @chatroom = Chatroom.new(chatroom_params)
    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to @chatroom }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end
  def show
    @chatroom = Chatroom.find(params[:id])
    render json: @chatroom.chats
  end
  private
  def chatroom_params
    params.require(:chatroom).permit(:email, :name)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
  end
  def create
    @chat = Chat.new(chat_params)
    respond_to do |format|
      if @chat.save
        format.json { render :show, status: :created, location: @chat }
      else
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end
  def new
    @chat = Chat.new
  end
  def show
    @chats = Chat.where(chatroom_id: params[:id])
    respond_to do |format|
      if @chats
        format.json { render :chats, status: :ok }
      else
        format.json { render json: @chats.errors, status: :unprocessable_entity }
      end
    end
  end
  private
  def chat_params
    params.require(:chat).permit(:message, :name, :chatroom_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chatrooms/create.html.erb
<h1>Chatrooms#create</h1>
<p>Find me in app/views/chatrooms/create.html.erb</p>

app/views/chatrooms/index.html.erb
<div class="container-fluid full-page bg-dark position-relative">
  <div class="jumbotron jumbotron-fluid bg-transparent text-white">
    <div class="container">
      <h1 class="display-4">Southville Solutions</h1>
      <p class="lead">Your ultimate software destination.</p>
    </div>
  </div>
  <div class="popup-trigger bg-info text-white col-3">
    <p>Chat with support</p>
  </div>
  <div class="popup-wrapper bg-white col-3 p-0 collapse">
    <div class="popup-head bg-info p-1">
      <p>Close chat window</p>
    </div>
    <div class="start-chat-wrapper bg-light px-1 mt-5">
      <%= form_with(model: @chatroom, format: :json, id: 'start-chat-form') do |form| %>
        <div class="field">
          <%= form.text_field :name, id: :name, class: "form-control", required: true, placeholder: "Enter your name" %>
        </div>
        <div class="field">
          <%= form.email_field :email, id: :email, class: "form-control mt-3", required: true, placeholder: "Enter your email" %>
        </div>
        <div class="actions">
          <%= form.submit 'Start chat', class: "btn btn-primary btn-block mt-2" %>
        </div>
      <% end %>
    </div>
    <div class="chat-wrapper bg-light px-1 collapse">
      <div class="chats">
      </div>
      <div class="chat-form">
        <%= form_with( scope: :chat, url: chats_path, format: :json, id: 'chat-form') do |form| %>
          <div class="field">
            <%= form.text_field :message, id: :message, class: "form-control", required: true, placeholder: "Enter your message" %>
            <%= form.hidden_field :name, id: :name %>
            <%= form.hidden_field :chatroom_id, id: :chatroom_id %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/chatrooms/new.html.erb
<h1>Chatrooms#new</h1>
<p>Find me in app/views/chatrooms/new.html.erb</p>

app/views/chatrooms/show.html.erb
<h1>Chatrooms#show</h1>
<p>Find me in app/views/chatrooms/show.html.erb</p>

app/views/chats/create.html.erb
<h1>Chats#create</h1>
<p>Find me in app/views/chats/create.html.erb</p>

app/views/chats/index.html.erb
<div class="container-fluid full-page position-relative">
  <div class="row">
    <div class="col-3 col-md-2 bg-dark full-page px-1 py-2 sidebar">
      <% @chatrooms.each do |chatroom| %>
        <% if chatroom.chats.any? %>
          <div class="dashboard-sidebar-chat bg-info">
            <%= link_to chatroom.email, chat_path(id: chatroom.id), remote: true, class: 'sidebar-chat' %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-9 col-md-10 bg-light full-page container">
      <h5 class="mt-4">👈 Select a chat from the sidebar to load the message</h5>
      <div class="admin-chat-wrapper">
        <h3 class="user-email mt-5"></h3>
        <div class="chat-form">
          <div class="admin-chats"></div>
          <%= form_with( scope: :chat, url: chats_path, format: :json, id: 'admin-chat-form') do |form| %>
            <div class="field">
              <%= form.text_field :message, id: :message, class: "form-control", required: true, placeholder: "Enter your message" %>
              <%= form.hidden_field :name, id: :name, value: 'Southville Sol support' %>
              <%= form.hidden_field :chatroom_id, id: :chatroom_id %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chats/new.html.erb
<h1>Chats#new</h1>
<p>Find me in app/views/chats/new.html.erb</p>

app/views/chats/show.html.erb
<h1>Chats#show</h1>
<p>Find me in app/views/chats/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SouthvilleSol</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>